import type { Metadata } from "next";
import { auth } from "@/lib/auth";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  
  const session = await auth();

  if(!session) {
    
  }

  return (
    <section className="min-h-full flex flex-col">
        {children}
    </section>
  );
}
